# valor = float(input('qual foi seu valor gasto?'))
# if valor >= 250:
#    desconto =  0.16 * valor
#    resultado = valor - desconto
#    print(f'seu valor com desconto é de  {resultado} ') 
# else:
#     print (f'neste caso não a desconto {valor} ' )

quantidade = float(input('qual quantidade tem em estoque ? '))
pedido = float(input('qual pedido do cliente ? '))
peso= float(input('qual peso total do pedido ? '))

if pedido <= 200 and peso <=50
    print('seu pedido esta sendo separado')
else :
    print('exedeu estoque da loja ')

         



    

